import textstat

ans_1 = ("""""")
ans_2 = ("""""")
ans_3 = ("""""")
ans_4 = ("""""")
ans_5 = ("""""")
ans_6 = ("""""")
ans_7 = ("""""")
ans_8 = ("""""")
ans_9 = ("""""")
ans_10 = ("""""")
ans_11 = ("""""")
ans_12 = ("""""")
ans_13 = ("""""")
ans_14 = ("""""")
ans_15 = ("""""")
ans_16 = ("""""")
ans_17 = ("""""")
ans_18 = ("""""")
ans_19 = ("""""")
ans_20 = ("""""")
ans_21 = ("""""")
ans_22 = ("""""")
ans_23 = ("""""")
ans_24 = ("""""")
ans_25 = ("""""")
ans_26 = ("""""")
ans_27 = ("""""")
ans_28 = ("""""")
ans_29 = ("""""")
ans_30 = ("""""")
ans_31 = ("""""")
ans_32 = ("""""")
ans_33 = ("""""")
ans_34 = ("""""")
ans_35 = ("""""")

answers = {1:ans_1, 2:ans_2, 3:ans_3, 4:ans_4, 5:ans_5, 6:ans_6, 7:ans_7, 8:ans_8, 9:ans_9, 10:ans_10, 11:ans_11, 12:ans_12, 13:ans_13, 14:ans_14, 15:ans_15, 16:ans_16, 17:ans_17,
           18:ans_18, 19:ans_19, 20:ans_20, 21:ans_21, 22:ans_22, 23:ans_23, 24:ans_24, 25:ans_25, 26:ans_26, 27:ans_27, 28:ans_28, 29:ans_29, 30:ans_30, 31:ans_31, 32:ans_32,
           33:ans_33, 34:ans_34, 35:ans_35}
while True:
    answer = int(input('Which Id would you like to see?: '))
    if answer ==1:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_1, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_1))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_1))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_1))
        print ("Syllable count: ") 
        print (textstat.syllable_count(ans_1))
    elif answer ==2:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_2, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_2))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_2))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_2))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_2))
    elif answer ==3:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_3, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_3))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_3))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_3))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_3))
    elif answer ==4:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_4, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_4))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_4))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_4))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_4))
    elif answer ==5:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_5, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_5))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_5))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_5))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_5))
    elif answer ==6:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_6, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_6))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_6))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_6))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_6))
    elif answer ==7:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_7, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_7))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_7))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_7))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_7))
    elif answer ==8:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_8, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_8))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_8))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_8))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_8))
    elif answer ==9:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_9, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_9))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_9))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_9))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_9))
    elif answer ==10:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_10, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_10))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_10))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_10))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_10))
    elif answer ==11:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_11, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_11))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_11))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_11))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_11))
    elif answer ==12:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_12, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_12))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_12))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_12))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_12))
    elif answer ==13:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_13, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_13))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_13))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_13))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_13))
    elif answer ==14:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_14, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_14))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_14))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_14))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_14))
    elif answer ==15:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_15, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_15))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_15))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_15))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_15))
    elif answer ==16:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_16, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_16))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_16))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_16))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_16))
    elif answer ==17:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_17, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_17))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_17))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_17))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_17))
    elif answer ==18:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_18, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_18))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_18))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_18))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_18))
    elif answer ==19:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_19, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_19))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_19))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_19))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_19))
    elif answer ==20:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_20, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_20))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_20))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_20))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_20))
    elif answer ==21:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_21, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_21))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_21))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_21))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_21))
    elif answer ==22:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_22, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_22))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_22))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_22))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_22))
    elif answer ==23:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_23, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_23))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_23))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_23))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_23))
    elif answer ==24:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_24, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_24))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_24))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_24))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_24))
    elif answer ==25:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_25, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_25))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_25))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_25))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_25))
    elif answer ==26:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_26, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_26))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_26))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_26))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_26))
    elif answer ==27:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_27, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_27))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_27))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_27))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_27))
    elif answer ==28:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_28, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_28))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_28))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_28))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_28))
    elif answer ==29:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_29, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_29))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_29))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_29))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_29))
    elif answer ==30:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_30, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_30))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_30))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_30))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_30))
    elif answer ==31:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_31, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_31))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_31))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_31))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_31))
    elif answer ==32:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_32, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_32))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_32))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_32))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_32))
    elif answer ==33:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_33, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_33))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_33))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_33))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_33))
    elif answer ==34:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_34, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_34))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_34))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_34))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_34))
    elif answer ==35:
        print ("Lexicon count (without punctuation): ")
        print(textstat.lexicon_count(ans_35, removepunct=True))
        print("Sentence Count: ")
        print (textstat.sentence_count(ans_35))
        print("Flesch reading ease score: ")
        print(textstat.flesch_reading_ease(ans_35))
        print("Dale-Chall Readability: ")
        print(textstat.dale_chall_readability_score(ans_35))
        print ("Syllable count: ")
        print (textstat.syllable_count(ans_35))
    else:
        print("Invalid number")

